version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config/firebaseKey.json:/app/db/config/firebaseKey.json:ro
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
